### ISSUE TITLE
How to install and usage? 

### ISSUE THREAD

**Issue by elvismdev** [Kreatys/PdfParserBundle#1]
After installing it via Composer, how do I must add it to `AppKernel.php`? Can you give me some guidance on working installation and specific usage?

Thank you

**Comment by jcrombez** [comment]
like any other bundle : 

```php
<?php
// app/AppKernel.php

public function registerBundles()
{
    $bundles = array(
        // ...
        new Kreatys\PdfParserBundle\KreatysPdfParserBundle(),
        // ...
    );
}
```

then you can use the library with the service named "kreatys.pdf_parser"

**Comment by elvismdev** [comment]
Cool thank you, I think you should add some documentation about the usage inside Symfony here on your Readme.md. Do you mind if my team sends some collab? @lele140686 @parenthesislab

**Comment by jcrombez** [comment]
Not sure what you mean by "send some collab"

**Comment by elvismdev** [comment]
Yeah sorry for that, collab == collaboration, meaning a PR to your README.md with some guidances for lost people like us xD

**Comment by jcrombez** [comment]
ok :)
